name: PR checker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Types
        run: npm run types:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.13.0"

      - uses: actions/setup-java@v2.1.0
        with:
          distribution: "adopt"
          java-version: "14"
          java-package: jre

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache firebase emulators
        id: cache-firebase
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase
          restore-keys: |
            ${{ runner.os }}-firebase

      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

      - name: Tests
        run: npm run test